name: Docker Build Backend Master

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the image
      run: docker build --tag datastaxdevs/cws-week8-backend:latest ./week8-k8s-in-the-cloud/getting-started-with-astra-python
    - name: Login to hub.docker.com
      run: docker login -u ${{ secrets.DOCKER_USER }} -p  ${{ secrets.DOCKER_PASSWORD }}
    - name: Push the image
      run: docker push datastaxdevs/cws-week8-backend:latest
